version: "3.0"
services:
  dockerapp:
    env_file: 
      - ./app/.env
    environment: 
      - ENVIRONMENT=PRODUCTION
#     build: wardnath/dockerapp
#     ports:
#       - "5000:5000"
#     depends_on:
#       - mongo
#       - redis
#   mongo:
#     image: mongo:3.7.2
#   redis:
#     image: redis:3.2.0
