version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201708-01
    steps:
      - checkout
      # - run:
      #     name: Install dependencies
      #     command: |
      #       apk add --no-cache py-pip=9.0.0-r1
      #       pip install docker-compose==1.15.0
      - run:
          name: copy ENV vars to .env file
          command: |
            echo "ENVIRONMENT=${ENVIRONMENT}" > app/.env
      - run:
          name: Run tests
          command: |
            docker build --no-cache . ;
            docker-compose up -d ;
            docker-compose run dockerapp pyI thon test.py ;
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag project_dockerapp $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            docker tag project_dockerapp $DOCKER_HUB_USER_ID/dockerapp:latest
            docker push $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/dockerapp:latest

